[package]
name = "lrmux"
version = "0.1.0"
edition = "2024"
description = "A modern, fast, minimal-dependency terminal multiplexer"
license = "MIT"
readme = "README.md"
repository = "https://github.com/roji-net/lrmux"
homepage = "https://github.com/roji-net/lrmux"
keywords = ["terminal", "multiplexer", "tmux", "byobu"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
nix = { version = "0.31", features = ["term", "process", "event", "fs", "user"] }
libc = "0.2"
vte = "0.15"
toml = { version = "1.1", features = ["parse", "display"] }
serde = { version = "1", features = ["derive"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = "2"
rcgen = "0.14"
sha2 = "0.11"
tungstenite = { version = "0.30", default-features = false, features = ["handshake"] }

[dev-dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
